### ISSUE TITLE
getChargerStatus() sometimes never returns

### ISSUE THREAD

**Issue by wolfc01** [cliviu74/wallbox#25]
Hi,

in a long running session, once per second my software calls the getChargerStatus() method. Due to (I  presume: network connection problems), the getChargerStatus call never returns (5 hours waiting now...) , nor an exception is thrown. Is there some timeout I can set to avoid this?

Best regards
Carl.

**Comment by nickspacek** [comment]
The wallbox library uses the requests library for its HTTP communications, and the default is no timeout (wait indefinitely).

You can pass `requestGetTimeout` to the `Wallbox` constructor and it will pass that to the requests calls.

https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts

**Comment by cliviu74** [comment]
Thanks @nickspacek for the solution. Closing this issue for now.
