### ISSUE TITLE
set energy cost

### ISSUE THREAD

**Issue by angelbarrera92** [cliviu74/wallbox#26]
Hi!

The module is amazing :) i see it is being used by HomeAssistant.
I would like to create an automation to dinamically set the charging price based on an input from another module (pvpc from spain).

To do that this module needs to expose a way to set it :)
Do you mind if I contribute to this module with this feature?

Thanks

**Comment by cliviu74** [comment]
All contributions greatly appreciated @angelbarrera92, thanks! 
I'll review this asap.

**Comment by cliviu74** [comment]
This is merged, grand job @angelbarrera92
