### ISSUE TITLE
Implement reset function

### ISSUE THREAD

**Issue by Leventionz** [cliviu74/wallbox#28]
Hello,

I would very much like it if there was a switch in home assistant to reset my wallbox. On occassion I have some issues communicating with it and I find that resetting the unit fixes the problem, often for days at a time.

If there were a switch to force a restart of the wallbox unit in home assistant I would be able to automate the reset process.

If this feature already exists, is it possible to expose this within home assistant or provide steps on how I could achieve this.

Many thanks

**Comment by Leventionz** [comment]
I think this may well be possible as there is a reset function on my.wallbox.com

![image](https://github.com/cliviu74/wallbox/assets/24567397/9fd191e3-d029-4d4a-9002-5e0ae01791bd)

**Comment by cliviu74** [comment]
Looking at it

**Comment by cliviu74** [comment]
Released

**Comment by Leventionz** [comment]
Thank you!
