### ISSUE TITLE
Install issue Raspi 

### ISSUE THREAD

**Issue by mvroosmalen1970** [cliviu74/wallbox#3]
Hi 

Tried to install on a Raspi, but failed:
raspberrypi:~ $ pip install wallbox
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting wallbox
  Could not find a version that satisfies the requirement wallbox (from versions: )
No matching distribution found for wallbox

Any suggestions. On my Linux laptop the install was successful

Mark

**Comment by mvroosmalen1970** [comment]
Could it be that wallbox requires python >-3.7 
I;ve installed Python 2.7.16 and upgrade my cause problems.... Can I install on 2.7 and debug?

Mark

**Comment by cliviu74** [comment]
Hey @mvroosmalen1970 , the wallbox library requires python 3.7 or older. Due to features incompatible with python 2, like f strings and updated upstream libraries it won't be possible to make this work in Python 2.

**Comment by cliviu74** [comment]
Closing and module requires newer version of python than the ones used by reporter.

**Comment by mvroosmalen1970** [comment]
Hi cliviu74,

The solution for me was to use pip3 install instead of pip. I
successfully installed Python 3 next to 2

Mark

2021-05-04 23:14 GMT+02:00, cliviu74 ***@***.***>:
