### ISSUE TITLE
Add support for reading and writing charging schedules

### ISSUE THREAD

**Issue by nanomad** [cliviu74/wallbox#38]

**Comment by tmenguy** [comment]
ok found Charles for iOS will look at it :)

**Comment by nanomad** [comment]
Yep, I actually decompiled an old APK version

**Comment by tmenguy** [comment]
ok, used Charles proxy on iOS and got all the new stuffs too like enabling eco smart, boost, etc

**Comment by tmenguy** [comment]
but I'll wait for our beach of PR to be approved before going further .....
