### ISSUE TITLE
Issue : Wallbox HA integration is hanging randomly

### ISSUE THREAD

**Issue by tmenguy** [cliviu74/wallbox#39]
The HA integration is hanging indefinitely from time to time : this is due to the lack of  timeout by default in the wallbox lib (as recommended by the requests lib), and I other times getting this exception:
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://user-api.wall-box.com/users/refresh-token

**Comment by cliviu74** [comment]
This has been reverted as per comments on https://github.com/cliviu74/wallbox/pull/40
