### ISSUE TITLE
Feature: when stopping a charge manually, have a way to be able to set back the charger in schedule or ecosmart mode

### ISSUE THREAD

**Issue by tmenguy** [cliviu74/wallbox#41]
Hi,

I can code it myself, but the feature is not available on the my.wallbox.com website so I have no idea how to reverse engineer it, do you do wireshark on the device with the app?

BR
Thomas

**Comment by tmenguy** [comment]
ok found Charles for iOS will look at it :)

**Comment by tmenguy** [comment]
it seems that we have the action : remote-action : 9 :) 
(well I have played with the remote action stuff ... trying 4 ... VERY bad idea .... it has done a factory reset of my Wallbox :) )

**Comment by cliviu74** [comment]
This change has been merged.
