### ISSUE TITLE
Code broken by latest PR 

### ISSUE THREAD

**Issue by tmenguy** [cliviu74/wallbox#47]
See line 206 / 213 of wallbox.py it seems setIcpMaxCurrent and getChargerSchedules have been badly merged

**Comment by tmenguy** [comment]
pushed in #46 for a quick fix :)

**Comment by cliviu74** [comment]
Thanks, I saw the test was failing and fixed it now. Please revert this.

**Comment by cliviu74** [comment]
Fixed by #48

**Comment by tmenguy** [comment]
ok no pb will get your fix in #46 (but it is probably the same ... the #46 is making sense no?

**Comment by cliviu74** [comment]
It does make sense and that was a good catch. I already had the change in my local cache and was about to push when I saw your message. 
Sorry for the issues, luckaly I have a test job that notifies me if there's syntax issues.
This is fixed now anyways, looking at the other changes when I have a bit of time today.

**Comment by tmenguy** [comment]
cool, they are simple : timeout for everyone (POST/GET/PUT) a fix in case of refresh token refresh error (this one is hard to reproduce, must be long, multiple days,  with no HA reboot ... and well I assume you are like me you reboot a lot your setup :) )
