### ISSUE TITLE
Bugfix - put/post requests don't respect timeout

### ISSUE THREAD

**Issue by cliviu74** [cliviu74/wallbox#49]
The put/post requests don't observe the requestTimeout parameters  as it's not being set.

This was discovered by @tmenguy and changed in #46

**Comment by cliviu74** [comment]
fixed in #51

**Comment by cliviu74** [comment]
Thanks @tmenguy for the work.

**Comment by tmenguy** [comment]
great ... so now. the #46 is ok, I just rebased on your last merge
