### ISSUE TITLE
wallbox module stopped working

### ISSUE THREAD

**Issue by jeremy-compostella** [cliviu74/wallbox#9]
the pauseChargingSession(), resumeChargingSession() and setMaxChargingCurrent() function do not work even though they don't generate any error. has the API changed ?

**Comment by jeremy-compostella** [comment]
This is a very weird situation. I have two Android devices with the latest version of the Wallbox application installed:
1. On my Pixel XL2 the application works fine, if I hit the play button, the charging starts, if I change the charging rate it does change the charging rate
2. On my Lenovo tablet, the application seems to work but changing the charging rate does stay and the resume and pause button do not do anything.
I have been able to place a proxy between my Lenovo tablet and api.wall-box.com and the API seems very close to what is used in this wallbox.py module. Unfortunately, my Pixel XL2 won't let me install a system wide certificate and I can't use the proxy to monitor the traffic.
I decompiled the wallbox APK application but I could not find anything different compared to what is done by your module.

I have really no idea what is going on. Does the API still work well for you ?

**Comment by jeremy-compostella** [comment]
It turns out that if I turn off bluetooth it does not work on the Pixel2 XL either and if I turn off bluetooth on my Lenovo tablet then it starts working (even though the UI does not update properly). I also noticed that if I use https://my.wallbox.com/ it does not work either.
The only way to get it to work is to actually use bluetooth.

**Comment by cliviu74** [comment]
Hi @jeremy-compostella indeed the pause charge and charging current selection functions stopped working. The problem is with the web api not executing those commands. They work OK on bluetooth but unaccessible via the web ui or mobile app via WiFi. I'll try to raise a support issues with Wallbox.

**Comment by jeremy-compostella** [comment]
I also raised a ticket with them yesterday. This morning, my car is already
smartly charging (I have a python service automatically charging and
setting the charging rate depending on my solar panel production and house
power usage).

It means that they most likely resolve the issue :)

Regards,
Jeremy

**Comment by cliviu74** [comment]
Hey Jeremy, thanks for confirming the issue is resolved. 
I will mark this as an issue with the upstream API. Please reopen if you think it's not sorted.
